### ISSUE TITLE
Create a Js function to show humize number

### ISSUE THREAD

**Issue by christiankakesa** [KIOO-Official/kioo-airdrop#1]
Show a JS function print big number to short format:

```
1020 => 1.02K
1020000 => 1.02M
1020000000 => 1.02B
1020000000000 => 1.02T
```

**Comment by glody007** [comment]
`function printBigNumberToShortFormat(number) {
  const formatter = Intl.NumberFormat("en", { notation: "compact",  maximumFractionDigits: 2  });
  return formatter.format(number);
}`

**Comment by glody007** [comment]
```
function printBigNumberToShortFormat(number) {
  const formatter = Intl.NumberFormat("en", { notation: "compact",  maximumFractionDigits: 2  });
  return formatter.format(number);
}
```

**Comment by christiankakesa** [comment]
Create a git branch like: "create-js-func-to-humanize-number".
Add your function in app.js in helper section, it must be a functor: `const myfunc = () => {}`.
Comment the commit with the ID of the issue like: `my commt #1`.
Push the branch on Origin and create a pull request on github.com and assign me as reviewer.

**Comment by christiankakesa** [comment]
Nice.

In NumberFormat, set locale to `undefined` and add `minimumFractionDigits: 2`.
Rename the functor name to `PrintBigNumberToShortFormat`.

Sound good to me after this updates.
